api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api-platform/resources'
            - '%kernel.project_dir%/src/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apikey: {
                "type": "header",
                "name": "Authorization"
            }

    title: Symfony API Platform
    version: 1.0
    show_webby: false
